### ISSUE TITLE
Cannot log in to Perplexity using email-login

### ISSUE THREAD

**Issue by stracker-phil** [prateekkeshari/peek-ai#10]
Maybe I'm missing something, but I cannot sign in to my existing Perplexity account (using an email-address).

Perplexity sends a magic login link via email. When I click that link, it's opened in the default browser and logs me in, but the session in Peek is not updated, i.e. I'm still using it as a guest there.

It seems like a problem caused by Perplexity's passwordless email login.

To solve this, you could provide a way to copy and paste the login link from the email to the Peek window to complete the login process inside Peek.

**Comment by prateekkeshari** [comment]
Hey there. Thanks for highlighting. Will release in the next update. Testing now 
![image](https://github.com/prateekkeshari/peek-ai/assets/24781460/fa0f7513-d3ea-4e4a-8bd7-540283a417e3)

**Comment by prateekkeshari** [comment]
This is done and ships later this week @stracker-phil. Thanks!

**Comment by greatvivek11** [comment]
Still Unable to login using mail from Arc browser.After providing email, a new blank tab opens but it doesn't redirect to the code page. Similarly, upon clicking the link in verification email, it redirects to perplexity login page.
