### ISSUE TITLE
Peek captures important keyboard shortcuts (even when minimized)

### ISSUE THREAD

**Issue by stracker-phil** [prateekkeshari/peek-ai#12]
The keyboard shortcuts in Peek AI are currently a bit counterproductive:

* `CMD+D` is a common keyboard shortcut in code editors, and Peek-AI captures this shortcut system-wide (even when the Peek window is not visible)   
As a result, the shortcut is not handled by VSCode, Sublime Text, PhpStorm, etc.
* `CMD+arrow` is a system shortcut to move the cursor to the end of the line; currently, Peek will switch to the next/prev AI instead of moving the cursor to the start/end of the prompt text field.  
I would prefer CMD+1, CMD+2 etc to explicitly select the first/second/etc AI, regardless on which AI or tool I currently use
* `CMD+J` is a shortcut that's used by our task management app to create a new task. This is an app-specific keyboard shortcut that Peek AI interferes with, as opening the Peek window always creates a draft task that I need to manually discard using the mouse

→ I hope that you can find a way to allow customization of keyboard shortcuts soon, to address the issue

Also, the issue with `CMD+D` is a bit strange, as that's not a shortcut that has any effect in Peek, but is intercepted by it for some reason.

**Comment by prateekkeshari** [comment]
hey, custom shortcut is on my list. will ship as soon as I can.
Replicated the CMD+D error - it's a bug, shipping a new update for a fix.

**Comment by prateekkeshari** [comment]
@stracker-phil command + numbers are system shortcuts for a lot of people (for example I use command + 4 to open cursor). I am considering command + ctrl + right and left arrow keys.

Anyway, when I ship a custom shortcut thing, it should be easier.

**Comment by stracker-phil** [comment]
Thanks for the swift update 👍 Really appreciate that CMD+D is working again 😀 

Since the CMD+D behavior was the only real bug, and you're working on a custom shortcut integration, I'll just mark this issue as closed.
