### ISSUE TITLE
Request custom shortcuts

### ISSUE THREAD

**Issue by Mrered** [prateekkeshari/peek-ai#2]
The current shortcut ⌘J conflicts with the VS Code shortcut. I hope to be able to customize shortcuts! I sent you a private message on 𝕏 but haven't received any reply 🥲.

**Comment by prateekkeshari** [comment]
Heya, sorry about that! I don't see your DM on X, but not your fault and maybe just X being weird. That said, I am working on customizing shortcuts and will ship soon! :)

**Comment by prateekkeshari** [comment]
this is done! please get the new update 👍
