### ISSUE TITLE
[Bug] - Issues on multiple monitor setups

### ISSUE THREAD

**Issue by BugsWorld** [prateekkeshari/peek-ai#5]
When I click to open Peek Ai from the menubar of my 2nd monitor, it still opens on my main display. The popup should be opening on the same monitor where i'm clicking the menubar.

**Comment by prateekkeshari** [comment]
hey, thanks. Will work and drop a fix.

**Comment by prateekkeshari** [comment]
@BugsWorld are you able to drag it to the new monitor or no?

**Comment by BugsWorld** [comment]
> @BugsWorld are you able to drag it to the new monitor or no?

Yes, the way it currently works is that you can drag it anywhere you want and whenever you click the menubar icon, the popup opens back up at that exact spot. It would be nice to have a additional option so that the popup opens at a "Default" place on the screen (basically right below the menubar icon). This way, it would allow it to open up on the secondary display right below the menubar icon as well. 

This is very crucial for multi-monitor setups

**Comment by prateekkeshari** [comment]
Makes sense. Thank you! Are you willing to give the beta version of this a try? Would love to receive any other additional feedback around it.

**Comment by BugsWorld** [comment]
Sure

**Comment by prateekkeshari** [comment]
Hey @BugsWorld, try this (assuming you are on M1): https://github.com/prateekkeshari/peek-ai/releases/download/3.0.3-beta/Peek-3.0.3-beta-arm64-mac.zip

If not, here's intel version: https://github.com/prateekkeshari/peek-ai/releases/download/3.0.3-beta/Peek-3.0.3-beta-mac.zip

**Comment by prateekkeshari** [comment]
hey @BugsWorld, you can try the [beta release here for apple silicon macs.](https://github.com/prateekkeshari/peek-ai/releases/download/3.0.4-beta/Peek-3.0.4-beta-arm64-mac.zip)

If you are on intel mac, you can [try it here.](https://github.com/prateekkeshari/peek-ai/releases/download/3.0.4-beta/Peek-3.0.4-beta-mac.zip)

**Comment by BugsWorld** [comment]
Hey man, just tried it (intel mac)

So it's now able to pop-up on my second display. But few notes:

- When I left click on the menubar icon, it opens the right-click menu, and then I have to click on "open" for it to open. This should be fixed so left-click opens the pop-up and right click opens the right click menu.

- Once the pop-up is open, there is no way to close it.. It just stays open forever. I can just re-open it on the other display but can't actually close it. Left clicking doesn't do anything. And even if Floating window is disabled, it still doesn't close the pop-up when I click away, it just goes to the back.

- In the final release, it would be nice if you could add a toggle for the pop-up to open at a default location on the screen or disable to open it wherever the user last moves the pop-up. And it would be nice if it remembers separately for each screen (depending on which screen's menubar you click). So for example, you turn on the toggle in the settings and that enables it to open at the default location on both screens (Below the menubar icon), or you disable the toggle to open it wherever you last moved it (different for each screen).

I like the new icon though.

**Comment by prateekkeshari** [comment]
hey @BugsWorld - fixed the first. The second behavior is minimizing behavior. You can do that with Command + M. The toggle option isn't feasible at this point, but I'll explore it later. Try the new beta here: https://we.tl/t-wZUtx1FYYl

**Comment by prateekkeshari** [comment]
oops, sorry - here you go: https://we.tl/t-cl6hXjirtG

**Comment by prateekkeshari** [comment]
I can test this more thoroughly next week (when I have access to my second monitor) and give you a version that works best. For now, will ship this with a bunch of new improvements. You already have the new version, so enjoy and thanks again for your kind feedback :)
